### PR TITLE
Start moving to https for updates

### PR DESCRIPTION
**Pull request by kithrup**
Merge in the changes (both mine and William's) for ticket #25707.

### CODE REVIEW

**Review by william-gr — APPROVED** [review]
LGTM, we need to make sure py-requests is distributed in the installation image. If memory serves me well there was a follow up commit in build repo.

**Comment by amotin** [comment]
Sean, I suppose you need to merge also 2a7891f59a28293aa69023830288d3a7576aecdf -- "Lazy import requests to not require it in installer image".

**Comment by kithrup** [comment]
Thanks!  Doing a build with that and will make sure it works.

**Comment by kithrup** [comment]
I found a bug with the code, that prevented it from working properly when there was an error.  I'll need to get that change back into master.

**Review by amotin — APPROVED** [review]
Looks good to me.

**Pull request merged**
